import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import CategoriesList from '@/components/Categories/CategoriesList'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <div className=' min-h-screen flex flex-col'>
          <Navbar/>

          <div className='flex-auto' >
          {children}
          </div>

          <div>
           <Footer/>
          </div>
        </div>
      </body>
    </html>
  )
}
